name: Compile QMK
on: [workflow_dispatch]

jobs:
  build:
    name: Compile QMK
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false

    steps:
    - name: Checkout QMK
      uses: actions/checkout@v3.3.0
      with:
        repository: qmk/qmk_firmware
        ref: develop
        submodules: true

    - name: Build
      continue-on-error: true
      run: qmk -v compile -kb marksard/rhymestone/rev1 -km default -e CONVERT_TO=blok

    - name: Archive
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        retention-days: 60
        name: firmware
        path: |
          *.hex
          *.bin
          *.uf2

